"""comments, project_members, projects, tasks, users table added

Revision ID: 34e763334399
Revises: 50cd12969c46
Create Date: 2025-03-30 20:14:48.876040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34e763334399'
down_revision: Union[str, None] = '50cd12969c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('ADMIN', 'PROJECT_MANAGER', 'TEAM_MEMBER', name='userrole'),
               nullable=True)
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'PROJECT_MANAGER', 'TEAM_MEMBER', name='userrole'),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
