"""role added to user

Revision ID: 50cd12969c46
Revises: 885263105e82
Create Date: 2025-03-29 16:12:03.056079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50cd12969c46'
down_revision: Union[str, None] = '885263105e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=255), nullable=False))
    op.drop_column('users', 'super_admin')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('super_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
