"""db models changed

Revision ID: f6e6f10c754b
Revises: 0c46eb0905d3
Create Date: 2025-04-01 19:47:36.666112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e6f10c754b'
down_revision: Union[str, None] = '0c46eb0905d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_members_ibfk_1', 'project_members', type_='foreignkey')
    op.drop_constraint('project_members_ibfk_2', 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tasks_ibfk_2', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_ibfk_1', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_1', 'tasks', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key('tasks_ibfk_2', 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key('project_members_ibfk_2', 'project_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('project_members_ibfk_1', 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_1', 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key('comments_ibfk_3', 'comments', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('comments_ibfk_2', 'comments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
